### PR TITLE
LC-674 - Upgrade parquet-avro for CVE

### PR DESCRIPTION
**Pull request by kiratraynor**
Upgrade org.apache.parquet:parquet-avro from 1.15.0 to 1.15.1.

[NVD - CVE-2025-30065](https://nvd.nist.gov/vuln/detail/CVE-2025-30065)

### CODE REVIEW

File: lucille-plugins/lucille-parquet/pom.xml [hunk 1]
```diff
@@ -33,7 +33,7 @@
     <dependency>
       <groupId>org.apache.parquet</groupId>
       <artifactId>parquet-avro</artifactId>
-      <version>1.15.0</version>
+      <version>1.15.1</version>
```
Comment (mrwrench24) [inline lucille-plugins/lucille-parquet/pom.xml:36]: unfortunately, this didn't resolve the Parquet issue I had noticed. This doesn't seem to work with Hadoop 3.4.1, but that is the most recent (Oct. 2024) version of Hadoop-common available. 
However, this upgrade **specifically** is not the cause of the error. Not sure what the best approach forward here would be.

Comment (mrwrench24) [reply lucille-plugins/lucille-parquet/pom.xml:36]: Calls out to `ParquetFileReader.open` cause:
`java.lang.NoClassDefFoundError: org/apache/hadoop/mapreduce/lib/input/FileInputFormat`

**Review by mrwrench24 — APPROVED** [review]
